# -*- coding: utf-8 -*-

# GLOBAL VARIABLES


xCo = []
yCo = []
nClsMat = None
nCboMat = None
dist = None
connectNodes = None
headBC= None
times = []
ve3 = None
velDi3 = None
tt = None
readQ = None
head = None
inn = None
typBC = None
nodElems = None
surface = None
wDepth = None
basem = None
readBasem = []
dispL = None
dispT = None
diff = None
surf = None
readConClastBC = None
readClastQ = None
q = None
conClastBC = None
subsidence = None
readtypBC = None
clastQ = None
poroIni = None
poroMin = None
wMin = None
cn = None
tInitStep = 0.01
grid = None
wDisp = None
density = None
vCritic = None
setClast = None
area = None
conClast = None
veloNode = None
slope = None
slopeNode = None
vCriticE = None
setClastE = None
specPopMin=None
interMatrix=None
birth=None
nutriCom=None
cboProd=None
specPopIni=None
specPop=None
porosity=None
ss=None
wDepthE = None
totalArea = None
seaLevel = 0.0
hIni = None
iniSeaLev = 0.0
totalTime = 0.0
cTime = 0.0
dt = 0.0
prevTotTime = 0.0
tol = None
chicken = None
iniConcNutrients = None
totalVolSedOut = None
totalVolSedSusp = None
totalVolSedSuspJtiMat = None
nti = None
nCol = 0
nRow = 0
nNode = 0
nElem = 0
jti = None
bw = None
nl = None
nTotalMat = None
factorType = None
numEq = None
nutrients = None
nSiliMat = None
sediName = []
stepTime = None
sl = None
waySL = None
depo = None
directory = None
projectName = None
modelingTime = None
comClasticSedi = False
comTransport = False
comCarboSedi = False
comIsostasy = False
comMassBalance = False
comErosion = False
comCompaction = False
comSubsidence = False
totalVolSedOut = 0
totalVolSedOut_2 = 0
deptFactorX = None
deptFactorY = None
slopeFactorX = None
slopeFactorY = None
flowFactorX = None
flowFactorY = None
clsFactorX = None
clsFactorY = None
nutrFactorX = None
nutrFactorY = None
factorWD = None
factorVL = None
factorSL = None
factorNU = None
factorCL = None
envFactor = None
eros = None